# Generated by Django 3.0.5 on 2020-04-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200421_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dis_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
