# Generated by Django 3.0.5 on 2020-04-22 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_dis_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dis_price',
            new_name='discount_price',
        ),
    ]
