# Generated by Django 3.0.5 on 2020-04-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200421_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a type of food stuff which you can be purchase on our website.'),
            preserve_default=False,
        ),
    ]
